# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumhaz <- function(Time, lambda, death_point) {
    .Call(`_FASTcure_cumhaz`, Time, lambda, death_point)
}

haz_ <- function(Time, event, death_point, wexpb) {
    .Call(`_FASTcure_haz_`, Time, event, death_point, wexpb)
}

